server:
  port: 8088
  ssl:
    key-store: server.keystore
    key-alias: tomcat
    enable: true
    key-store-password: 123456
    key-store-type: JKS
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.137/xy_unmannedhotel120?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xyzh2018
# mapper location
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml